### ISSUE TITLE
make https upload primary data upload method

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#325]
Before HTTPS upload can be merged in, update documentation and examples to make this the primary way users can upload data.

This also includes removing Globus upload pathway in first example doc (this task is from miro. get more context from Ben or Ari about what doc this is)

# Tasks

- [x] #210 
- [x] Check to see if any other example notebooks need to be updated
- [x] Update GitBook docs
- [x] cut a release (update foundry versions accordingly) and email UWisc collaborators about it

**Comment by ascourtas** [comment]
Note this is taking longer than expected because there have been various errors and discrepancies in the notebooks and documentation that I've been fixing along the way

**Comment by ascourtas** [comment]
Notebook in review, some docs changes have been merged but not all -- needs final documentation push

**Comment by ascourtas** [comment]
No other notebooks needed updating. Officially done! From this story, other stories have been made to update other inconsistencies in notebooks and documentation
