### ISSUE TITLE
Update Foundry documentation

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#327]
_As a User, I want to be able to easily navigate the Foundry documentation and quickly figure out how to publish and load datasets_

Context: We as developers have noticed that some users still seem to struggle even when pointed to the documentation

Most notable sticking points:
- hard to know what file inputs are supported at a glance
- Hard to figure out exactly what is needed to publish without reading everything (it'd be helpful to have a quick overview example in the docs)

# Assumptions
- We still use Foundry GitBook

# Acceptance criteria
1. Collaborators can find answers to their questions without consulting us first
2. User can quickly and easily answer the following questions:
- 1. What file types are supported for data publishing?
- 2. How do the data need to be formatted?
- 3. What functions do I evoke to publish?
- 4. What functions do I evoke to load data?

# Tasks

See this Miro board for exact updates to make: https://miro.com/app/board/uXjVPrIdUhE=/?moveToWidget=3458764549361933874&cot=14 

Probably want to make some of these subtasks and list them out here 

- [ ] Update example notebooks
   - [ ] Link to proper documentation and take out references to source code (ex: `Metadata` section of Data Publishing notebook
   - [ ] Add context for the limits of HTTPS dataset publishing -- ie at what point the user would have to use Globus Connect Client
   - [ ] remove model publishing guide from `main`

**Comment by ascourtas** [comment]
bumping to next sprint due to syntax changes

**Comment by blaiszik** [comment]
This should be clear to work on now. The old syntax will still work, we just support skipping `load()` now by providing the info in the constructor

**Comment by ascourtas** [comment]
Waiting on current Foundry PRs to be merged

**Comment by blaiszik** [comment]
Is this still blocked or completed?
