### ISSUE TITLE
Increase test coverage for HTTPS upload functionality

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#329]
_As a Developer, we want to make sure functionality (especially core functionality) is rigorously tested and updated_

# Assumptions
- HTTPS functionality moves from `foundry` to `mdf_connect_client`

# Tasks

- [ ] Add tests to cover different file structures a user could upload
- [ ] Add test to pull down dataset after publication to load it and actually use it 
- [ ] Update existing tests to use a proper metadata format for the test data involved

# Acceptance criteria
1. Tests outlined above are made and all pass
