### ISSUE TITLE
Design Accelerate group brand and product brands

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#331]
_As Developers/Product Owners, we must create a cohesive brand and messaging for the Accelerate ecosystem of products and services (think "Apple ecosystem") such that users know exactly which product to use for their needs, and can readily find that information_

This is still in the design/exploratory phase. Additional stories will be borne from this one for technical implementations; this story is focused more on product design, both for Accelerate as a whole and for our separate products (eg Foundry, Garden, MDF, etc)

See [Branding Google doc](https://docs.google.com/document/d/1JMGW9uxjiflADPveCZsnKpv3zJP51FKY65k42hIGYZ8/edit#heading=h.jf1jzivh9872) for more thoughts/details

```[tasklist]
### Tasks
- [x] Branding discussion brainstorm together
- [x] Write copy for Accelerate website (KJ) (see here) -- #332
- [x] Review copy (Ari)
```
# Acceptance criteria
1. Have an agreed upon vision of the Accelerate brand and initial design of website layout
2. Have website copy agreed upon between each other

**Comment by kjschmidt913** [comment]
Link to website copy: https://docs.google.com/document/d/17S-nLXPeliJKrTQ-VTfqsiBvKovxnApsRcYowaRs2Tw/edit#

**Comment by ascourtas** [comment]
Reviewed copy! content addition suggestion was a "What is accessible science?" page explaining things like reproducibility, findability, etc. Currently a WIP in the google doc linked above with amendments from KJ.

**Comment by ascourtas** [comment]
Done for now! Additional work to be done in #337
