### ISSUE TITLE
Create visuals to communicate Accelerate product vision

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#387]
_As a Product Owner, we want to be able to effectively communicate with both our team and the external world about how our products fit together. This issue will focus on internal communication_

Related to #383 

```[tasklist]
### Tasks
- [ ]  Create very high-level product-focused Miro board diagram of how services/products link up in the Accelerate universe (ex: can you access foundry datasets through Garden?). This will be more focused on user flow than any technical implementation, and can serve as the basis for future technical diagrams
- [ ] Ben B, Ari, KJ to synch on product vision, needs, and decisions (add document here)
- [ ] Create a presentation for the team
```

# Assumptions:
1. We are ready to have these discussions in the first place
2. 

# Acceptance Criteria
1. Given any of our internal team members (eg Accelerate) hears about "Foundry", "MDF", or "Garden", they understand A) The high level purpose of that product, and B) How that product relates to others in the Accelerate ecosystem
2. All team members are given access to this information and it is stored somewhere accessible

**Comment by ascourtas** [comment]
Blocked on #397
