### ISSUE TITLE
Reevaluate Foundry class structures

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#395]
_As a User, I want it to be intuitive to use Foundry without reading through the docs or spending a lot of time on examples. As a Developer, I want it to be easy to maintain the Foundry SDK_

Currently, the class structure in the Foundry SDK makes it difficult to add some quality of life or feature updates that would benefit the user's experience, such as improved load vs load_data clarification, multi-dataset workflows, etc. 

Reevaluate the current class structures in the Foundry SDK to see if there's a better pattern we can follow 

# Assumptions
1. Familiarity with the current Foundry SDK and class structures 
2. Familiarity with OOP best practices
3. Familiarity with user workflows and use cases for Foundry (see here: https://miro.com/app/board/uXjVPrIdUhE=/?moveToWidget=3458764558322356672&cot=14 )

# Acceptance criteria
1. Problems and potential solutions are well documented
2. Given the problems and potential solutions have been identified, we can create pseudocode that captures what the refactor would look like
3. Given the pseudocode, we can determine the amount of work it would require to accomplish the refactor, and have updated the Foundry roadmap and stories accordingly

# Tasks
- [x] Meet to discuss options and potential (captured here: https://miro.com/app/board/uXjVPrIdUhE=/?moveToWidget=3458764562928081684&cot=14 )
- [x] Write up pseudocode to show what it would look like (Steve: https://gist.github.com/blue442/cbf04969d448e011b2d6ccacc1cb0ec9)
- [ ] Define several initial stories
- [ ] Update Foundry roadmap/timeline

**Comment by ascourtas** [comment]
@blue442 have you heard back from @blaiszik on the pseudocode yet?

**Comment by blue442** [comment]
> @blue442 have you heard back from @blaiszik on the pseudocode yet?

I have not.

**Comment by ascourtas** [comment]
Early sprint, have story writing session for Foundry class revamp
