### ISSUE TITLE
Plan out Foundry refactor

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#398]
_As Developers, we want to make sure the Foundry SDK is structured well for both other developers and our users_

We've discussed refactoring the Foundry class structures based on findings from #379 and #187 (see the [refactor discussion here](https://miro.com/app/board/uXjVPrIdUhE=/?moveToWidget=3458764562928081684&cot=14)) . We just need to finalize the gameplan to do so

# Assumptions
1. The refactor aligns with our product vision for Foundry (see [Miro board roadmapping](https://miro.com/app/board/uXjVPrIdUhE=/?moveToWidget=3458764556306397906&cot=14))
2. The refactor will not be overly arduous 

# Acceptance criteria
1. Met with Ben and he approves
2. Story writing session completed; have concrete, well-scoped stories for current sprint and future sprints

# Tasks

- [x] Discuss with Ben B in Accelerate Meeting to get pseudocode approval
- [x] Schedule and have Story Writing Meeting 
- [x] Create use case examples to ensure the refactor will account for all user needs (ex: using DOI right away to get dataset object)
