### ISSUE TITLE
Prototype data publication user experience

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#404]
_As a Publisher, I want to be able to easily publish my dataset without question about what metadata are needed or how to add it_

Per [Miro board discussions](https://miro.com/app/board/uXjVPrIdUhE=/?moveToWidget=3458764565184052393&cot=14), create Pydantic classes for `FoundrySchema`, `FoundryDatacite` such that instances of each can be passed into the `FoundryDataset()` constructor in order to create a dataset object for publication. Update the existing publishing [notebook](https://github.com/MLMI2-CSSI/foundry/blob/main/examples/publishing-guides/dataset_publishing.ipynb) and its associated example data to create a new example flow like the one defined below. The notebook should not actually publish the dataset to MDF; the Pydantic Classes just need to capture the necessary state (eg metadata).

The goal of this issue is to ascertain how it will feel for the user with this new flow. Actual publication will be handled in #403 

## Additional context
Note that some of the schema-related work was established in #218, and the Pydantic class `FoundryMetadata` was created -- we determined this was too vague, and will be restructuring it into `FoundrySchema` and `FoundryDatacite` accordingly.

`FoundrySchema` should correspond to the schema defined in [`data-schemas/schemas/projects.json`](https://github.com/materials-data-facility/data-schemas/blob/12bb3c7da2a5d8667e5cdb8fe90f18b77094af4d/schemas/projects.json#L111)
`FoundryDatacite` should correspond to the schema defined in [`data-schemas/schemas/dc.json`](https://github.com/materials-data-facility/data-schemas/blob/12bb3c7da2a5d8667e5cdb8fe90f18b77094af4d/schemas/dc.json)

## Desired user flow

The flow should be as follows: 

```
f = FoundryClient()
dc = FoundryDatacite(title="MyTitle", authors=['steve', 'ari', 'kj'])

schema = FoundrySchema(splits=[Split('test', path='/test'),
                  Split('train', path='/train')]
              keys=[FoundryKey('lastname', type='str', description='Last Name')
     )


d = FoundryDataset(datacite=dc, schema=schema)

d.add_data("globus://foo.bar")

f.publish(d)
```

# Assumptions:
1. We will be using defining the Pydantic class schemas based on the data schemas already outlined at https://github.com/materials-data-facility/data-schemas/tree/12bb3c7da2a5d8667e5cdb8fe90f18b77094af4d/schemas 
2. We are not changing the existing key-value pairs used in current iterations of Foundry metadata schema definitions (see the [mdf-schemas repo](https://github.com/materials-data-facility/data-schemas/blob/master/schemas/projects.json#L111) and the Foundry Pydantic model [FoundryMetadata](https://github.com/MLMI2-CSSI/foundry/blob/main/foundry/models.py#L93C13-L93C13))
3. We will address the primary on loading dataset functionality (#399 ) before publishing datasets

# Acceptance Criteria
1. Publishing notebook that uses the above Pydantic classes to mock the publication of a sample foundry dataset (does not need to actually publish)
2.  Given the publishing notebook using these Pydantic classes, we as a team can ascertain whether or not the usage experience aligns with our user needs and product vision.
3. Given the discussion about the flow experience, we have a clear action plan for next steps

```[tasklist]
### Tasks
- [x] implement `FoundrySchema` and `FoundryDatacite` Pydantic classes
- [x] update a publishing notebook to use this flow of dataset definition to see how it feels for a user; take a screenshot
- [x] iterate on Pydantic class design as necessary if the changes are minor, or create a new issue for more in-depth changes
```

**Comment by ascourtas** [comment]
Method of attack:

> ✨Decision: What if we actually move the cache to be a member of teh FoundryClient class, divorcing it from constructing as part of the FoundryDataset __init__() 
This means that there is one cache per FoundryClient instance 
Reference to Foundry.cache is passed in as an optional arg to FoundryDataset()
This is critical so that the user can still create a FoundryDataset object
dataset = FoundryDataset(name, datacite, foundry_schema) (see issue for good formatting)
This also means the FoundryDataset class does not require the forge_client, transfer_client, etc, which is good for separation of purpose 
Decision: we aren’t concerned about the corner case described below
If it ever comes up (unlikely), we can make an issue
