### ISSUE TITLE
address remaining JOSS comments

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#419]
In addition to the opened issues by marshallmcdonnell, review any remaining comments at https://github.com/openjournals/joss-reviews/issues/5467 that may have been missed.

# Tasks
- [x] Determine if comments remain
- [x] Address them accordingly

**Comment by ascourtas** [comment]
Reviewers confirmed there are no remaining changes to be made. Last steps:

- [ ] release changes
- [ ] Zip code
- [ ] Upload zip to Zenodo, with the following reqs: 
  - [ ]     The title of the archive is the same as the JOSS paper title
  - [ ]     That the authors of the archive are the same as the JOSS paper authors
- [ ] Reply to review thread with Zenodo DOI

**Comment by ascourtas** [comment]
Additional steps were required:

- [ ] fix DOI issues 
- [ ] reupload zip -- of `joss` branch this time, so need to redo it
- [ ] re-release (figure out what this means, since the `joss` branch is not a released branch)

**Comment by ascourtas** [comment]
More steps:

- [ ] fix citation errors
- [ ] reupload zip of `joss` branch to Zenodo
- [ ] get confirmation from JOSS
