### ISSUE TITLE
Update loading documentation for user feedback

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#447]
_As a User, I need good documentation to know what's going on, especially after a major code refactor that will break all of my stuff_

We've made a lot of changes in the Refactor, but we need to update the documentation so users can actually get using it! 

# Assumptions:
1. We're just doing this for loading, not publishing atm until the publishing changes are merged into `dev`
2. This will go out in an alpha release with the loading changes, but currently those are all in `dev` 
3. We're still using GitBook 
4. Related to #410 

# Acceptance Criteria
1. Given the documentation, a close collaborator (eg UW) can 
2. The documentation accurately reflects the current state of the `dev` codebase

# Tasks
- [x] update all GitBook docs related to loading/downloading datasets 
- [x] double check example notebooks are correct (see Investigation below)
  - [ ] update notebooks accordingly
- [ ] ensure that GitBook descriptions of metadata, data schemas, etc match the new formats 
- [x] generate class- and method-level documentation based on docstrings
